#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Restore Lighthouse production data from a backup directory (generated by backup-origin-to-lighthouse.sh).

Usage:
  ./scripts/migration/restore-lighthouse-from-backup.sh /opt/new-api-src/backups/origin/<timestamp>

This script will:
  - (Optional) create a pre-restore backup under /opt/new-api-src/backups/pre-restore/<timestamp>
  - stop docker compose project "new-api"
  - replace /opt/new-api-src/data and /opt/new-api-src/logs from the backup
  - recreate the postgres volume and restore DB dump
  - bring services back up and verify /api/status

Env:
  REPO_DIR             default: /opt/new-api-src
  COMPOSE_PROJECT      default: new-api
  POSTGRES_CONTAINER   default: postgres
  PG_SUPERUSER         default: newapi
  PG_DB                default: new-api
  PRE_RESTORE_BACKUP   default: true
  APP_PORT             default: 3000
  SERVER_ADDRESS       optional: https://api.aisever.art (or api.aisever.art)
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

BACKUP_DIR="${1:-}"
if [ -z "$BACKUP_DIR" ]; then
  echo "ERROR: missing BACKUP_DIR" >&2
  usage >&2
  exit 2
fi

REPO_DIR="${REPO_DIR:-/opt/new-api-src}"
COMPOSE_PROJECT="${COMPOSE_PROJECT:-new-api}"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-postgres}"
PG_SUPERUSER="${PG_SUPERUSER:-newapi}"
PG_DB="${PG_DB:-new-api}"
PRE_RESTORE_BACKUP="${PRE_RESTORE_BACKUP:-true}"
APP_PORT="${APP_PORT:-3000}"
SERVER_ADDRESS="${SERVER_ADDRESS:-}"

require_file() {
  local path="$1"
  if [ ! -f "$path" ]; then
    echo "ERROR: missing file: $path" >&2
    exit 2
  fi
}

require_file "$BACKUP_DIR/app.env"
require_file "$BACKUP_DIR/new-api.dump"
require_file "$BACKUP_DIR/postgres-globals.sql"
require_file "$BACKUP_DIR/app-data.tgz"

cd "$REPO_DIR"

if [ "$PRE_RESTORE_BACKUP" = "true" ]; then
  TS="$(date +%Y%m%d-%H%M%S)"
  PRE_DIR="$REPO_DIR/backups/pre-restore/$TS"
  mkdir -p "$PRE_DIR"
  docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}" > "$PRE_DIR/docker-ps.txt" || true
  docker volume ls > "$PRE_DIR/docker-volumes.txt" || true
  if docker ps -a --format '{{.Names}}' | grep -qx "$POSTGRES_CONTAINER"; then
    docker exec "$POSTGRES_CONTAINER" pg_dumpall -U "$PG_SUPERUSER" --globals-only > "$PRE_DIR/postgres-globals.sql" 2>/dev/null || true
    docker exec "$POSTGRES_CONTAINER" pg_dump -U "$PG_SUPERUSER" -d "$PG_DB" -F c > "$PRE_DIR/new-api.dump" 2>/dev/null || true
  fi
  tar -czf "$PRE_DIR/repo-data.tgz" -C "$REPO_DIR" data 2>/dev/null || true
  tar -czf "$PRE_DIR/repo-logs.tgz" -C "$REPO_DIR" logs 2>/dev/null || true
fi

echo "==[1/6] Stop services ==" >&2
docker compose -p "$COMPOSE_PROJECT" down

echo "==[2/6] Restore data/logs directories ==" >&2
TS2="$(date +%Y%m%d-%H%M%S)"
[ -d "$REPO_DIR/data" ] && mv "$REPO_DIR/data" "$REPO_DIR/data.pre-restore-$TS2" || true
[ -d "$REPO_DIR/logs" ] && mv "$REPO_DIR/logs" "$REPO_DIR/logs.pre-restore-$TS2" || true
mkdir -p "$REPO_DIR/data" "$REPO_DIR/logs"
tar -xzf "$BACKUP_DIR/app-data.tgz" -C "$REPO_DIR"
[ -f "$BACKUP_DIR/app-logs.tgz" ] && tar -xzf "$BACKUP_DIR/app-logs.tgz" -C "$REPO_DIR" || true

echo "==[3/6] Write runtime .env (permissions 600) ==" >&2
umask 077
cp "$BACKUP_DIR/app.env" "$REPO_DIR/.env"

echo "==[4/6] Recreate postgres volume ==" >&2
docker volume rm "${COMPOSE_PROJECT}_pg_data" >/dev/null 2>&1 || true
docker volume rm "${COMPOSE_PROJECT}-pg_data" >/dev/null 2>&1 || true
docker volume rm "new-api_pg_data" >/dev/null 2>&1 || true

echo "==[5/6] Start postgres+redis ==" >&2
docker compose -p "$COMPOSE_PROJECT" up -d postgres redis

echo "== Wait for postgres ==" >&2
for _ in $(seq 1 60); do
  if docker exec "$POSTGRES_CONTAINER" pg_isready -U "$PG_SUPERUSER" -d postgres >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

echo "==[6/6] Restore database ==" >&2
docker cp "$BACKUP_DIR/postgres-globals.sql" "$POSTGRES_CONTAINER:/tmp/postgres-globals.sql"
docker cp "$BACKUP_DIR/new-api.dump" "$POSTGRES_CONTAINER:/tmp/new-api.dump"
docker exec "$POSTGRES_CONTAINER" bash -lc "psql -U \"$PG_SUPERUSER\" -d postgres -f /tmp/postgres-globals.sql || true"
docker exec "$POSTGRES_CONTAINER" bash -lc "pg_restore -U \"$PG_SUPERUSER\" -d \"$PG_DB\" --clean --if-exists /tmp/new-api.dump"
docker exec "$POSTGRES_CONTAINER" rm -f /tmp/postgres-globals.sql /tmp/new-api.dump || true

if [ -n "$SERVER_ADDRESS" ]; then
  if [[ "$SERVER_ADDRESS" != *"://"* ]]; then
    SERVER_ADDRESS="https://${SERVER_ADDRESS}"
  fi
  SERVER_ADDRESS="${SERVER_ADDRESS%/}"
  SERVER_ADDRESS_ESCAPED="${SERVER_ADDRESS//\'/''}"

  echo "== Update ServerAddress option: $SERVER_ADDRESS ==" >&2
  docker exec -i "$POSTGRES_CONTAINER" psql -U "$PG_SUPERUSER" -d "$PG_DB" >/dev/null <<SQL
INSERT INTO options (key, value)
VALUES ('ServerAddress', '${SERVER_ADDRESS_ESCAPED}')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
SQL
fi

echo "== Start new-api ==" >&2
docker compose -p "$COMPOSE_PROJECT" up -d new-api

echo "== Verify ==" >&2
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${APP_PORT}/api/status" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
curl -fsS "http://127.0.0.1:${APP_PORT}/api/status" >/dev/null

echo "RESTORE_OK backup_dir=$BACKUP_DIR"
